=== noahpresler/semesterly/parsing/library/schemas/instructor.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Section",
  "description": "Semesterly Section JSON definition",
  "type": "object",
  "properties": {
    "kind": {
      "enum": [ "instructor" ]
    },
    "school": {
      "allOf": [
        {
          "$ref": "definitions.json#/school"
        }
      ],
      "properties": {
        "code": {}
      },
      "additionalProperties": false
    },
    "classes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "course": {
            "allOf": [
              {
                "$ref": "course.json#/"
              }
            ],
            "properties": {
              "code": {}
            },
            "additionalProperties": false,
            "required": [ "code" ]
          },
          "section": {
            "allOf": [
              {
                "$ref": "section.json#/"
              }
            ],
            "properties": {
              "code": {}
            },
            "additionalProperties": false,
            "required": [ "code" ]
          },
          "additionalProperties": false
        },
        "minItems": 1
      }
    },
    "name": {
      "oneOf": [
        {
          "type": "string",
          "maxLength": 200
        },
        {
          "type": "object",
          "properties": {
            "first": {
              "type": "string",
              "maxLength": 100
            },
            "last": {
              "type": "string",
              "maxLength": 100
            }
          },
          "additionalProperties": false,
          "required": [
            "first",
            "last"
          ]
        }
      ]
    },
    "title": {
      "type": "string"
    },
    "department": {
      "allOf": [
        {
          "$ref": "definitions.json#/department"
        }
      ],
      "properties": {
        "code": {},
        "name": {}
      },
      "additionalProperties": false
    },
    "email": {
      "allOf": [
        {
          "$ref": "definitions.json#/email"
        }
      ]
    },
    "homepage": {
      "allOf": [
        {
          "$ref": "definitions.json#/url"
        }
      ]
    },
    "office": {
      "type": "object",
      "properties": {
        "location": {
          "allOf": [
            {
              "$ref": "definitions.json#/location"
            }
          ],
          "properties": {
            "campus": {},
            "building": {},
            "room": {},
            "building_room": {},
            "where": {}
          },
          "additionalProperties": false
        },
        "hours": {
          "type": "array",
          "items": {
            "allOf": [
              {
                "$ref": "meeting.json#/"
              }
            ],
            "properties": {
              "course": {},
              "section": {},
              "dates": {},
              "days": {},
              "time": {},
              "location": {}
            },
            "additionalProperties": false
          }
        }
      }
    }
  },
  "required": [ "name" ]
}

=== noahpresler/semesterly/docs/source/developers/backend/includes/instructor.json
{
  "kind": "instructor",
  "name": {
    "first": "Peter",
    "last": "Froelich"
  },
  "school": {
    "code": "jhu"
  },
  "title": "Professor",
  "department": {
    "code": "CS"
  },
  "email": "phf@cs.jhu.edu",
  "homepage": "http://gaming.jhu.edu/~phf/",
  "classes": [
    {
      "course": {
        "code": "EN.400.418"
      },
      "section": {
        "code": "01"
      }
    },
    {
      "course": {
        "code": "EN.400.418"
      },
      "section": {
        "code": "02"
      }
    },
    {
      "course": {
        "code": "EN.400.420"
      }
    }
  ],
  "office": {
    "location": {
      "campus": "Homewood",
      "building": "Malone Hall",
      "room": "223"
    },
    "hours": [
      {
        "days": ["M", "W"],
        "time": {
          "start": "15:00",
          "end": "15:50"
        }
      },
      {
        "course": {
          "code": "EN.400.418"
        },
        "days": ["F"],
        "time": {
          "start": "11:00",
          "end": "11:50"
        },
        "location": {
          "building": "Shaffer",
          "room": "301"
        }
      }
    ]
  }
}
