=== noahpresler/semesterly/scripts/new_parser_library/schemas/meeting_only.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Individual Meeting",
	"description": "Semesterly Meeting JSON schema - individual",
	"allOf": [
		{
			"$ref": "meeting.json#/"
		}
	],
	"properties": {
		"kind": {},
		"school": {},
		"course": {},
		"section": {},
		"dates": {},
		"days": {},
		"time": {},
		"location": {}
	},
	"additionalProperties": false,
	"required": [
		"kind",
		"course",
		"section",
		"time"
	],
	"_comment": "'days' or 'dates' requirement nested into meeting structure"
}

=== noahpresler/semesterly/docs/source/developers/backend/includes/meeting.json
{
  "kind": "meeting",
  "school": {
    "code": "jhu"
  },
  "course": {
    "code": "EN.600.418"
  },
  "section": {
    "code": "01"
  },
  "days": ["M", "W", "F"],
  "time": {
    "start": "13:30",
    "end": "14:45"
  },
  "location": {
    "campus": "Homewood Campus",
    "building": "Shaffer Hall",
    "room": "301"
  }
}
